defaults: &defaults
  adapter: mongodb
  host: utage.sytes.net
  port: 27017
  username: rails3
  password: kotatsu3
  autocreate_indexes: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: trippal_dev
#  host: 192.168.0.200

test:
  <<: *defaults
  database: trippal_test
#  host: 192.168.0.200

# set these environment variables on your prod server
production:
  <<: *defaults
  database: trippal
